### ISSUE TITLE
Artisan's Consortium rep not working.

### ISSUE THREAD

**Issue by SiJiL82** [nawglan/wonder-rep#7] opened 2023-02-01 18:46 UTC
When I gain Artisan's Consortium rep, WonderRep logs out " WonderRep: 0 reputation with Artisan's Consortium - Dragon Isles Branch needed for Revered. (1 reputation gains left) A total of 835 reputation gained this session.  estimated time to Revered. "

![image](https://user-images.githubusercontent.com/65114782/216134819-a7f4fd91-67b3-4fda-812f-781488e9f825.png)

**Comment by nawglan** [comment] 2024-02-02 00:47
sorry this went unanswered for so long.   I can only think that it could be because that rep was minimized / collapsed in the reputation window.  There isn't anything in the code that would prevent it from working other than being impacted by what is collapsed in the rep window.

**Comment by nawglan** [comment] 2024-02-02 00:48
closing request.

**Comment by SiJiL82** [comment] 2024-02-02 21:43
The same thing happens with the new Azerothian Archives rep.
![image](https://github.com/nawglan/wonder-rep/assets/65114782/4c777ee2-039b-40c6-8a4b-27d231b08f37)
It's not minimised in the reputation window:
![image](https://github.com/nawglan/wonder-rep/assets/65114782/2a501fd7-7674-481a-b686-3849a0f03ad4)

**Comment by nawglan** [comment] 2024-02-04 18:01
Thanks, reopened the ticket.  I have been playing classic lately, will start a character on retail to see if I can reproduce.

**Comment by nawglan** [comment] 2024-02-15 01:00
What are the different ranks that are possible?  It could be that I'm just missing those.  found it.
1 | Neutral | 0 | 500
2 | Preferred | 500 | 2000
3 | Respected | 2500 | 3000
4 | Valued | 5500 | 7000
5 | Esteemed | 12500

**Comment by nawglan** [comment] 2024-02-15 01:15
hopefully adding those will fix the issue.

**Comment by SiJiL82** [comment] 2024-02-15 13:50
Unfortunately not 
![image](https://github.com/nawglan/wonder-rep/assets/65114782/3d5eefe7-6c8b-4f7d-a4aa-a6c44c689abd)

If what you posted before is what needs adding, it might be because they seem to have given all these reps different names for each level...

Azerothian Archives has
![image](https://github.com/nawglan/wonder-rep/assets/65114782/3fb79f2e-382d-44cf-807b-f1eef2508a5c)
Soridormi has
![image](https://github.com/nawglan/wonder-rep/assets/65114782/4ba66a84-ef28-4650-a381-2618333b46fc)
Glimmerogg Racer has 
![image](https://github.com/nawglan/wonder-rep/assets/65114782/ede7b553-11b4-4cae-b904-8224353cd235)

So you probably have fixed it for Artisan's Consortium (I can't test it any more, I'm at max rep!) but looks like it might need individual updates for every other faction that uses this format?

**Comment by SiJiL82** [comment] 2024-02-15 14:05
Just added this to `enUS.lua`
```
-- Glimmerogg Racer
L["Aspirational"] = true        --    0 -  700
L["Amateur"] = true             --  700 - 1400
L["Competent"] = true           -- 1400 - 2100
L["Skilled"] = true             -- 2100 - 2800
L["Professional"] = true        -- 2800+
```
and tested by doing a daily:
![image](https://github.com/nawglan/wonder-rep/assets/65114782/02607702-0c11-4496-9904-b53c59e7e6bb)
So looks like each individual rep with different names needs adding :( 

I'll create a fork and go through all the ones they've added that are like this over the weekend and send over a PR for you.

**Comment by nawglan** [comment] 2024-02-17 14:17
awesome. thanks for helping debug. 8)  I'll work on adding all of those.

**Comment by nawglan** [comment] 2024-02-17 15:57
there is more to do than just adding the strings to the localization files.  and looking at this spaghetti code, it really needs refactored. 8/

Thanks for offering to do a PR.

**Comment by nawglan** [comment] 2024-02-19 14:47
how's v2.2.4 working out for yall?

**Comment by SiJiL82** [comment] 2024-02-19 17:44
> how's v2.2.4 working out for yall?

Just tested with Azerothian Archives and Glimmerogg Racer reps, both working perfectly
![image](https://github.com/nawglan/wonder-rep/assets/65114782/b6a2235b-7e0d-42ef-af58-02d483ebeabe)

Thanks very much!

**Comment by nawglan** [comment] 2024-02-19 19:01
Glad to hear it!  Closing this. /fingers-crossed 8)

**Closed as completed by nawglan** 2024-02-19 19:01 UTC
